In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("taxi.csv")
dataset.shape

(27, 5)

In [3]:
dataset.head()

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0            15     1800000           5800                      50   
1            15     1790000           6200                      50   
2            15     1780000           6400                      60   
3            25     1778000           6500                      60   
4            25     1750000           6550                      60   

   Numberofweeklyriders  
0                192000  
1                190400  
2                191200  
3                177600  
4                176800

In [4]:
dataset.isnull().sum()

Priceperweek              0
Population                0
Monthlyincome             0
Averageparkingpermonth    0
Numberofweeklyriders      0
dtype: int64

In [5]:
#seperating dependent-independent variable
x=dataset.iloc[:,:4].values
x

array([[     15, 1800000,    5800,      50],
       [     15, 1790000,    6200,      50],
       [     15, 1780000,    6400,      60],
       [     25, 1778000,    6500,      60],
       [     25, 1750000,    6550,      60],
       [     25, 1740000,    6580,      70],
       [     25, 1725000,    8200,      75],
       [     30, 1725000,    8600,      75],
       [     30, 1720000,    8800,      75],
       [     30, 1705000,    9200,      80],
       [     30, 1710000,    9630,      80],
       [     40, 1700000,   10570,      80],
       [     40, 1695000,   11330,      85],
       [     40, 1695000,   11600,     100],
       [     40, 1690000,   11800,     105],
       [     40, 1630000,   11830,     105],
       [     65, 1640000,   12650,     105],
       [    102, 1635000,   13000,     110],
       [     75, 1630000,   13224,     125],
       [     75, 1620000,   13766,     130],
       [     75, 1615000,   14010,     150],
       [     80, 1605000,   14468,     155],
       [  

In [6]:
y=dataset.iloc[:,4].values
y

array([192000, 190400, 191200, 177600, 176800, 178400, 180800, 175200,
       174400, 173920, 172800, 163200, 161600, 161600, 160800, 159200,
       148800, 115696, 147200, 150400, 152000, 136000, 126240, 123888,
       126080, 151680, 152800], dtype=int64)

In [26]:
#split dataset into training and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_test

array([[     15, 1780000,    6400,      60],
       [     87, 1590000,   15600,     175],
       [     40, 1690000,   11800,     105],
       [    102, 1635000,   13000,     110],
       [     25, 1740000,    6580,      70],
       [     40, 1700000,   10570,      80],
       [     98, 1595000,   15200,     175],
       [     40, 1695000,   11600,     100],
       [     75, 1620000,   13766,     130]], dtype=int64)

In [8]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [9]:
import pickle #

In [10]:
pickle.dump(reg,open('taxi.pkl','wb')) #'wb'=write binary

In [12]:
#Test the model
model=pickle.load(open('taxi.pkl','rb')) #'rb'=read binary

In [22]:
y_pred = model.predict(x_test)
y_pred

array([188629.50339543, 136559.39301861, 167923.33044203, 126048.35876704,
       178953.09696641, 166223.49873765, 130975.62779069, 167971.3136973 ,
       141866.03727522])

In [25]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2*100) #r2*100 % accuracy

91.57379222488218


In [33]:
sample_prediction = model.predict([[16,1678000,6500,60]]).round(3) # predict method takes either a datafarame or a 2D numpy array(like 2 dimensional data)
print(sample_prediction)

[174779.025]
